export const LIMIT_DEFAULT_PRODUCTS_NUMBER_TO_FETCH = 10;
export const SKIP_DEFAULT_PRODUCTS_NUMBER_TO_FETCH = 0;
export const LIMIT_ADDED_PRODUCTS_NUMBER_TO_FETCH = 10;
export const SKIP_PRODUCTS_NUMBER_TO_FETCH = 10;
