import { StyleSheet } from "react-native";

export const stylesHome = StyleSheet.create({
    header: {
        textAlign: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFEC',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 10,
        margin: 5,
        fontSize: 20,
        fontWeight: "bold",
        //
    },
    sessionTimeInput: {
        backgroundColor: '#F1E4C3',
        textAlign: 'center',
        fontSize: 15,
        fontWeight: "400",
        margin: 20,
        borderRadius: 10,
        width: 80,
    },
    sessionTimeButton: {
        // textAlign: 'center',
        // justifyContent: 'center',
        backgroundColor: '#F1E4C3',
        fontSize: 15,
        fontWeight: "900",
        margin: 20,
        borderRadius: 10,
        width: 250,
    },
    sessionTimeOpacity: {
        alignItems: "center",
        fontSize: 15,
        fontWeight: "700",
        margin: 20,
        borderRadius: 10,
        // textAlign: "center",
    },
    viewSession: {
        justifyContent: "center",
        flexDirection: "row",
    },
    createTaskHeader: {
        backgroundColor: "#FFFFEC",
        alignItems: "center",
        fontSize: 15,
        fontWeight: "900",
        margin: 20,
        padding: 20,
        borderRadius: 10,
    },
    taskHeaderText: {
        fontSize: 15,
        fontWeight: "800",
    },
    taskInput: {
        backgroundColor: "#F1E4C3",
        textAlign: "center",
        alignItems: "center",
        alignContent: "center",        
        fontSize: 15,
        fontWeight: "600",
        margin: 10,
        marginVertical: 10,
        padding: 20,
        paddingVertical: 10,
        borderRadius: 10,
        width: '70%',
        left: '10%',
    },
    taskButton: {
        backgroundColor: "#F1E4C3",
        alignItems: "center",
        justifyContent: "center",
        fontSize: 15,
        fontWeight: "700",
        margin: 10,
        padding: 20,
        borderRadius: 10,
        width: '70%',
        left: '10%',
    },
    textButton: {
        fontSize: 15,
        fontWeight: "600",
    },

    inputs: {
        backgroundColor: "#FFFFEC",
        alignItems: "center",
        justifyContent: "center",
        fontSize: 15,
        fontWeight: "700",
        margin: 10,
        padding: 20,
        borderRadius: 10,
        width: '70%',
        left: '10%',
    },
    inputsText: {
        fontSize: 15,
        fontWeight: "600",
        padding: 5,
    },
    startSession: {
        backgroundColor: "#A9B388",
        alignItems: "center",
        justifyContent: "center",
        fontSize: 15,
        fontWeight: "700",
        margin: 20,
        padding: 20,
        borderRadius: 10,
        // width: '90%',
        // left: '2%',
    },
    startText: {
        fontSize: 15,
        fontWeight: "bold",
        padding: 5,
    },
    showHisotry: {
        backgroundColor: "#F1E4C3",
        alignItems: "center",
        justifyContent: "center",
        fontSize: 15,
        fontWeight: "700",
        margin: 20,
        padding: 20,
        borderRadius: 10,
    },
    historyText: {
        fontSize: 15,
        fontWeight: "bold",
        padding: 5,
    },
});
