import React from "react";
import { StyleSheet } from "react-native";


export const stylesLogin = StyleSheet.create({
    container: {
        flex: 1,
        margin: 20,
    },
    header: {
        marginBottom: 80,
    },
    title: {
        marginBottom: 10,
        fontWeight: "bold",
        fontSize: 33,
    },
    userInputs: {
        marginBottom: 20,
        flexDirection: 'column',
    },

    emailInput: {
        marginBottom: 20,
    },
    passwordTextInput: {
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 10,
        paddingRight: 0,
        color: 'black',
        textAlign: 'left',
        borderWidth: 1,
        borderRadius: 10,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
        marginRight: 0,
        borderRightColor: 'white',
        borderLeftColor: 'grey',
        borderTopColor: 'grey',
        borderBottomColor: 'grey',
        flex: 1,
    },
    passwordEye: {
        flexDirection: 'row',
    },
    eyeIcon: {
        borderWidth: 1,
        marginLeft: -10,
        borderLeftColor: 'white',
        borderRightColor: 'grey',
        borderTopColor: 'grey',
        borderBottomColor: 'grey',
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,

    },
    loginbutton: {
        marginTop: 20,
        backgroundColor: 'black',
        borderRadius: 10,
    },
    loginText: {
        color: 'white',
        textAlign: 'center',
        padding: 20,
        borderRadius: 20,
        fontWeight: "200",
    },
    textInput: {
        padding: 10,
        color: 'black',
        textAlign: 'left',
        borderColor: 'grey',
        borderWidth: 1,
        borderRadius: 10,
    },
    welcomingHeader: {
        color: 'grey',
        fontWeight:"400",
        fontSize: 16,
    },
    registerContainer: {
        flexDirection: 'row',
        justifyContent: "center",
    },
    bottom: {
        marginTop: 760,
        position: "absolute",
        alignSelf: "center"
    },
    registerationText: {
        color: 'grey',
        fontSize: 16,
    },
    errorEmail: {
        padding: 10,
        color: 'black',
        textAlign: 'left',
        borderColor: 'red',
        borderWidth: 1,
        borderRadius: 10,
    },
    errorPasswordNoIcon: {
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 10,
        paddingRight: 0,
        color: 'grey',
        textAlign: 'left',
        borderWidth: 1,
        borderRadius: 10,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
        marginRight: 0,
        borderRightColor: 'white',
        borderLeftColor: 'red',
        borderTopColor: 'red',
        borderBottomColor: 'red',
        flex: 1,
    },
    errorPasswordIcon: {
        borderWidth: 1,
        marginLeft: -10,
        borderLeftColor: 'white',
        borderRightColor: 'red',
        borderTopColor: 'red',
        borderBottomColor: 'red',
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,
    },
    validEmail: {
        padding: 10,
        color: 'black',
        textAlign: 'left',
        borderColor: 'green',
        borderWidth: 1,
        borderRadius: 10,
    },
    validPasswordNoIcon: {
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 10,
        paddingRight: 0,
        color: 'grey',
        textAlign: 'left',
        borderWidth: 1,
        borderRadius: 10,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
        marginRight: 0,
        borderRightColor: 'white',
        borderLeftColor: 'green',
        borderTopColor: 'green',
        borderBottomColor: 'green',
        flex: 1,
    },
    validPasswordIcon: {
        borderWidth: 1,
        marginLeft: -10,
        borderLeftColor: 'white',
        borderRightColor: 'green',
        borderTopColor: 'green',
        borderBottomColor: 'green',
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,
    },
    ErrorMessageText: {
        color: 'red',
    },
    textLabels: {
        color: 'black',
        fontWeight: "bold",
        fontSize: 18,
        marginVertical: 10,
    },


});
