import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
    container: {
        margin: 10,
        flexGrow:1,
    },
    product: {
        flex: 1,
        margin: 10,
    },
    screenHeaderAndArrow : {
        flexDirection: 'row',
    },
    headerArrowIcon: {
        marginBottom: 10,
        marginTop: 10,
        marginLeft: 20,
    },
    screenBody : {
        marginHorizontal: 30,
        marginTop: 10,
        marginBottom:30,
        flexDirection:'column',
    },
    saveIcon : {
        alignSelf: 'flex-end',
        position: 'absolute',
        zIndex: 1,
        backgroundColor: 'white',
        borderRadius: 10,
        top: 10,
        right: 10,
    },
    screenProductImage : {
        height: 400,
    },
    productTitle : {
        fontWeight: 'bold',
        fontSize: 20,
        color: 'black',
        marginTop: 10,
    },
    ratingAndReview : {
        flexDirection:'row',
        marginLeft: -15,
    },
    ratingScoreAndReviewNumber : {
        flexDirection:'row',
        marginVertical:16,
    },
    ratingScore : {
        fontWeight:'bold',
        color: 'black',
    },
    chooseSizePart : {
        marginVertical: 10,
    },
    chooseSizeText : {
        color: 'black',
        fontWeight:'bold',
        fontSize: 17,
        marginBottom: 5,
    },
    sizeOptionsIcons : {
        flexDirection: 'row',
        marginLeft: -18,
    },
    dividerLine : {
        borderBottomColor: 'grey',
        borderBottomWidth: 1,
    },
    priceAndAddToCartButton : {
        flexDirection:'row',
        marginBottom: 20,
        alignSelf: 'center',
        alignItems: 'center',
    },
    priceLabelAndNumber : {
        flexDirection: 'column',
        marginLeft: -110,
    },
    priceNumber : {
        fontWeight: 'bold',
        fontSize:20,
        color: 'black',
    },
    addToCartButtonContainer : {
        left: 120,
    },
    addToCartButton : {
        marginTop: 20,
        backgroundColor: 'black',
        borderRadius: 10,
    },
    addToCartButtonTextAndIcon : {
        flexDirection: 'row',
        alignItems: 'center',
    },
    addToCartText : {
        color: 'white',
        textAlign: 'center',
        padding: 20,
        borderRadius: 20,
        fontWeight: 'bold',
    },
        userInputs: {
        marginBottom: 20,
        flexDirection: 'column',
    },
    cardSecurityCode: {
    },
    cardExpiryDate: {
    },
    
    passwordTextInput: {
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 10,
        paddingRight: 0,
        color: 'grey',
        textAlign: 'left',
        borderWidth: 1,
        borderRadius: 10,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
        marginRight: 0,
        borderRightColor: 'white',
        borderLeftColor: 'grey',
        borderTopColor: 'grey',
        borderBottomColor: 'grey',
        flex: 1,
    },
    passwordEye: {
        flexDirection: 'row',
    },
    eyeIcon: {
        borderWidth: 1,
        marginLeft: -10,
        borderLeftColor: 'white',
        borderRightColor: 'grey',
        borderTopColor: 'grey',
        borderBottomColor: 'grey',
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,

    },
    AddCardButton: {
        marginTop: 20,
        backgroundColor: 'black',
        borderRadius: 10,
    },
    AddCardText: {
        color: 'white',
        textAlign: 'center',
        padding: 20,
        borderRadius: 20,
        fontWeight: 'bold',
    },
    cardNumberTextInput: {
        padding: 0,
        color: 'black',
        textAlign: 'left',
        borderColor: 'grey',
        borderWidth: 1,
        borderRadius: 10,
        backgroundColor: 'white',
    },
    cardSecurityCodeAndExpiryDateTextInput: {
        padding: 0,
        color: 'black',
        textAlign: 'left',
        borderColor: 'grey',
        borderWidth: 1,
        borderRadius: 10,
        backgroundColor: 'white',
    },
    welcomingHeader: {
        color: 'grey',
        fontWeight:"400",
        fontSize: 16,
    },
    registerContainer: {
        flexDirection: 'row',
        justifyContent: "center",
    },
    bottom: {
        marginTop: 760,
        position: "absolute",
        alignSelf: "center"
    },
    registerationText: {
        color: 'grey',
        fontSize: 16,
    },
    errorEmail: {
        padding: 10,
        color: 'black',
        textAlign: 'left',
        borderColor: 'red',
        borderWidth: 1,
        borderRadius: 10,
    },
    errorPasswordNoIcon: {
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 10,
        paddingRight: 0,
        color: 'grey',
        textAlign: 'left',
        borderWidth: 1,
        borderRadius: 10,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
        marginRight: 0,
        borderRightColor: 'white',
        borderLeftColor: 'red',
        borderTopColor: 'red',
        borderBottomColor: 'red',
        flex: 1,
    },
    errorPasswordIcon: {
        borderWidth: 1,
        marginLeft: -10,
        borderLeftColor: 'white',
        borderRightColor: 'red',
        borderTopColor: 'red',
        borderBottomColor: 'red',
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,
    },
    validEmail: {
        padding: 10,
        color: 'black',
        textAlign: 'left',
        borderColor: 'green',
        borderWidth: 1,
        borderRadius: 10,
    },
    validPasswordNoIcon: {
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 10,
        paddingRight: 0,
        color: 'grey',
        textAlign: 'left',
        borderWidth: 1,
        borderRadius: 10,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
        marginRight: 0,
        borderRightColor: 'white',
        borderLeftColor: 'green',
        borderTopColor: 'green',
        borderBottomColor: 'green',
        flex: 1,
    },
    validPasswordIcon: {
        borderWidth: 1,
        marginLeft: -10,
        borderLeftColor: 'white',
        borderRightColor: 'green',
        borderTopColor: 'green',
        borderBottomColor: 'green',
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,
    },
    ErrorMessageText: {
        color: 'red',
    },
    cardNumberText: {
        color: 'black',
        fontWeight: "bold",
        fontSize: 18,
        marginVertical: 10,
    },
    cardExpiryCodeAndSecurityCodeText: {
        color: 'black',
        fontWeight: "bold",
        fontSize: 18,
        marginVertical: 10,
    },
    AddNewCreditCardText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'black',
        marginVertical: 20,
    },
    AddNewCreditCardContainer:{
    },
    AddNewCardButton: {
        marginTop: 20,
        backgroundColor: 'black',
        borderRadius: 10,
        marginHorizontal: 40,
    },
    AddNewCardText: {
        color: 'white',
        textAlign: 'center',
        padding: 20,
        borderRadius: 20,
        fontWeight: 'bold',
    },
});
